---
title: "Chapter 6 - Demographic PVAs - Using Demographic Data to Build Stochastic Projection Matrix Models"
author: Mairin Deith
output: html_document
---

All previous examples have assumed that all individuals are identical - but we know that they have different survival and reproductive rates (e.g. larger individuals have higher survival and reproductive rates).

*Structured populations* - populations in which individuals differ in their vital rates; often classifies species into ages or stages

*Population projection matrix* - the principal way to describe the viability of structured populations

**Advantages**: 

- More accurate for populations with individual differences
- Help us to make more targeted management decisions based on age/stage (impossible with count-based model)

**Disadvantage**

- Contain more parameters, require more and different kinds of data (e.g. data from a demographic study of marked individuals)

This is less of a problem for keystone, umbrella, indicator, or high profile species with lots of research attention. 

## Overview of steps to build a projection matrix

1. Conduct a detailed demographic study of a set of marked individuals, measure survival, reproduction (state and number) over several years
2. Determine best state variable (age, stage, size) to classify individuals (both # of states and their boundaries)
3. Use demographic data to estimate vital rates for each class in each year
4. Use class-specific vital rate to build a projection population matrix (deterministic or stochastic)

The vital rates we want are **survival rate** (probability of survival), **state transition/growth rate**, **fertility rate** for each stage.

### Step 1. Demographic study

Demographic studies require following marked individuals for several years; not census counts. 

1. Mark individuals in a way that lets them be re-identified - **the markings should not influence survival or reproductive rates**, and the individuals should be representative of the entire population, i.e. randomize within the area, choose different classes of individuals through stratified random sampling
2. Marked individuals should be censused at regular intervals - the interval will be used to calculate vital rates and project into the future, typically over 1 year - should be conducted at the time of year when individuals are most obvious but *should take into consideration timing of reproduction so that fecundity can be confidently calculated, especially in birth-pulse populations when it is best to census right after the pulse. For birth flow populations, frequent checks of potentially reproductive individuals at time points within an inter-census interval may be necessary, or DNA fingerprinting could work*.
3. For some species (e.g. those that leave seed banks in the soil), the demographer may need to supplement above-ground census with a dormancy census. Another consideration must be juvenile dispseral - occurs over a short time period and can result in very low survival, making it difficult to identify surviving individuals
4. Collect data for as many censuses as the researcher/funds/time allow - **if possible, build a stochastic model** with enough censuses to estimate variability in vital rates. Add new marked individuals (newborns) to account for older adults that die off.

### Step 2. Establishing classes

Use demographic data to decide which state variable to use as a classifying variable (often done with preliminary data in the census study) - if it is continuous, break into discrete classes. 
There are a few ways to do this:

1. Classify by sex - most matrices only consider one sex, females, as it assumes that a single male fertilizes all females or that sex ratios are similar. Sex segregated models exist but require 2 sexes worth of data. 
2. Classify individuals by age, size, or stage - this is dictated by **practicality** (age may be difficult to ID compared to size/stage, morphological characters may be prominent - but it is possible to include multiple criteria like age AND stage, or age AND size) or **biology** (size is almost alwyas a better classifying variable than age if growth rates vary). The only requirement is that individuals *must only be in one class at a time; they are discrete*. 
An ideal state variable is **highly correlated** for all members of that state (this is a problem with size - it doesn't accurately predict vital rates if, e.g. plants with underground storage) and it should be **quick and accurate to measure** (if repeatability of measurements is low, there is little accuracy in state-based estimates for vital rates) - should balance practicality and accuracy. 
3. If classes are difficult to decide or if biological data are insufficient, graphical and statistical analysis of results can help - the appropriate tool depends on:
   1. If the vital rate is binary (survive/not), discrete but non-binary (birds may fledge 1,2,3, or 4 in a nest), or nearly continuous (very fecund species vary in effectively continuous manner among individuals)
   2. Whether the state variable is continuous (size/age) or discrete (stages)
```{r echo=F}
library(kableExtra)

rate <- c('Survival (discrete, binary)','Reproduction (discrete, non-binary)', 'Reproduction/growth (continuous-ish)')
classifier <- c('Age or size (continuous)', 'Stage (discrete)')
tests <- c('Logistic regression/hazard functions', 'GLM (e.g. Poisson regression)', 'Linear, polynomial, nonlinear regression', 'Log-linear models (G-test)','Log-linear models (G-test)', 'ANOVA (or nonparametric analogs)')

tests.df <- data.frame(matrix(tests, nrow=2, ncol=3))
colnames(tests.df) <- rate
rownames(tests.df) <- classifier

kable(tests.df) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```
*Note: simple logistic regression models predict steadily increasing/decreasing survival probabilities as a f'n of size/age. Logistic models can include more complex patterns like parabolic*


If two or more classifying variables are statistically related to vital rates (according to the statistical tests in the above table), you can decide which one to use based on:

- Stepwise regression to determine which feature is a better predictor of vital rates
- Test each individually with log-linear models (although requires that continuous state variables are discretized first)
- Assess the ability of each classifying variable to predict BOTH vital rates (fecundity and survival) - often one classifier will be a better predictor for both than the other
- If not, use $AIC_c$ based model selection, where $AIC_c$ is summed from the log-likelihoods of both models summed together (i.e. compute AIC for each state variable and choose the one with the lowest value):
$$ AIC_c = -2(logL_{max,s}+logL_{max,f}) + \frac{2p_s n_s}{n_s - p_s - 1} + \frac{2p_f n_f}{n_f - p_f -1 } $$
For example, assume that a simple logistic regression predicts survival vs. age, and a linear regression predicts fertility vs. age. 
The former regression has 2 parameters, the latter 3 (slope, intercept, residual variance). 
$logL_{max,f}$ can be calculated from the residual sum of squares, while the $logL_{max,s}$ can be output from statistical software.
We could then compare the calculated $AIC_c$ for the age-based model to the $AIC_c$ value for a stage-based model in which there is a quadratic regression for fertility and a hazard function for survival. 

4. Set class boundaries - for an age-structured model, widths of all classes must equal the interval between censuses; for stage-based classes, classes are synonymous with stages so this determines class boundaries. 
**Deciding the number of classes is important** - we want it to be large enough to encompass real differences in vital rates between classes (i.e. over-grouping can hide real differences) = more accurately reflects the time individuals require to advance from birth to reproduction caused by the processes of grwoth and matruation and have strong effects (e.g. if an organism takes 10 years to reproduce and we create 10 pre-reproductive classes to ensure individuals have to survive in each year from birth to reproduction; two pre-reproductive classes would result in some individuals to reproduce after 2 time intervals).
**Too many classes can also be problematic** - there may not be many individuals in each class and we reduce sample size. 

Generally speaking, start with a large number of biologically/management-relevant classes; look at scatterplots of vital rates to see any substantial inflection/alteration points, check to see if there are individuals in each class and if not, reduce the number of classes. There are more formal approaches, but they are in practice rarely used.

### Step 3. Estimating vital rates

#### Surival rates
Proportion of individuals in class $i$ in the last census that are still alive at the current census. For stage-based methods, sum the number of marked individuals *regardless of their new state* and divide by total number of survivors over total number of individuals. 
This can also be done with continuous variables - but this estimates survival for classes into which few individuals happen to fall = small sample size susceptible to variation and poor precision (can only estimate to the nearest 25%). 

For age or size based models, M+D recommend a 2-stage process:

1. Use the entire demographic data to perform logistic regression against age/size
2. Use the fitted regression equation to calculate survival for each class (pooling the data reduces the influence of chance variation and loss of precision and yields smooth changes in survival among age classes - *if there is a noticeable jump between young and older classes, it is possible to separate the youngest class then conduct the regression on the older classes only). 
    There are three ways to do this:
    1. Take the midpoint of each age/size class, substitute it into the logistic regression equation as the independent variable, then estimate survival on those midpoints (assumes that individuals are clustered around the midpoint)
    2. If the distribution of sizes in a class is skewed/not centrally clustered, use the median size from a random sample as the independent variable
    3. Use actual sizes for each individual, then average the survival rates within each class from the logistic regression results to reflect population-wide distribution of ages/sizes of individuals in the class
    

**Golden heather example** - we first choose class boundaries with reasonable number of plants in each of four size classes (plant area 0-25cm^2, 25-50, 50-100, 100+). 
The equation for logistic regression is $y = \frac{e^{b_0 + b_1x}}{1+e^{b_0 + b_1x}}$ where $y$ is predicted survival probability for plants with area $x$. 
The midpoint of each regression is the survival for that class.

#### State transition/growth rates
If individuals are classified by size or stage, we need to include transition/growth rates. 

The simplest way is to first place survivors from the marked population into a class transition table - columns = survivor's class at the previous census, rows = class at current census. 
Dividing each element in the table by the column total yields transition probabilities. 
**Note: this can be biased by small population sizes** - more sophisticated methods do exist though. 

#### Alternative ways for estimating survival rates/class transition rates using capture-recapture data and size vs. age relationships

It has been assumed that all marked individuals can be found - but this may not be true for small or highly mobile species in complex habitats. 
This introduces observation error and can complicate the interpretation of census data used in count-based PVAs - *we must also calculate the probability that a live, marked individual will not be captured in the following census.*

ML methods have been developed to deal with this problem - see MARK for example. 
Another method uses the length of time it takes for an individual to grow from one benchmark size to another (i.e. size class boundaries) and the probability of surviving over those years.
This gives the average time in each class and estimate of survival rate.

#### Fertility rate
The average number of offspring produced by an individual in each year **regardless of whether those offspring survive to the next class**. 
In stage class models, this is the arithmetic mean.
In age- or size-class models, they advocate using all individuals in the dataset to estimate reproduction simultaneously for all classes (like was done in for survival above). 

For organisms with multiple modes of reproduction (e.g. sexually produced seeds and vegetative ramets), there are different contributions of fecundity to growth rate.
Fecundity for each mode can be calculated as above.

### Step 4. Building the projection matrix
Number of rows **and** number of columns = number of classes. 
$a_{i,j}$ is the element in row $i$ and column $j$ of the matrix; or the probability that an individual of class $j$ in this census with contribute to an individual of class $i$ in the next. 
In other words, individuals transition from $j$ to $i$.
$$A = \begin{bmatrix} 
a_{1,1} & a_{1,2} & a_{1,3}\\
a_{2,1} & a_{2,2} & a_{2,3} \\
a_{3,1} & a_{3,2} & a_{3,3} 
\end{bmatrix}$$ 

When classed by age:

$$A_1  =
\begin{bmatrix} 
0 & F_2 & F_{3} & F_4\\
P_{1} & 0 & 0 & 0\\
0 & P_{2} & 0 & 0\\
0 & 0 & P_{3} & 0\\
\end{bmatrix}
$$

The sub-diagonal is probability of living to the next age.

When classed by size (but growth can vary, such that an individual can stay in the same stage $P_{1,1}$, grow to the next stage $P_{2,1}$, or revert to a smaller stage $P_{1,2}$
$$A_2  =
\begin{bmatrix} 
P_{1,1} & F_2+P_{1,2} & F_{3} & F_4\\
P_{2,1} & P_{2,2} & P_{2,3} & 0\\
0 & P_{3,2} & P_{3,3} & 0\\
0 & 0 & P_{4,3} & P_{4,4}\\
\end{bmatrix}
$$
When classed by stage (three pre-reproductive classes )
$$A_3  =
\begin{bmatrix} 
P_{1,1} & 0 & 0 & F_4\\
P_{2,1} & P_{2,2} & P_{2,3} & 0\\
0 & P_{3,2} & P_{3,3} & 0\\
0 & 0 & P_{4,3} & P_{4,4}\\
\end{bmatrix}
$$


The diagonal represents the probability of surviving and moving on to the next class; first row represents reproduction. 
Surviving adults can only remain in the adult class, but for some stage-based models it may be appropriate to have some individuals revert to an earlier stage (e.g. those that lose a breeding territory).

### Step 5. Building the matrix from underlying vital rates

Three types of vital rates:

1. $s_j$, survival rate for class $j$
2. $f_j$, fertility rate
3. $g_{i,j}$, probability that individual in class $j$ makes the transition to $i$ **given that it survives**

These are the vital rates, while $F$ and $P$ will serve as matrix elements. 

#### Class transition probabilities
**Age-structured models**
Survival is all we need to estimate class transitions - if they survive, they must enter a new age. 
Put class-specific survivals, $s_j$ along the principal subdiagonal of the matrix (e.g. $a_{j+1, j} = P_j = s_j$). 
All individuals in the oldest age class are assumed to die in the next year.

**Size/stage structured models**
State-based models can have progression or regression between states - $P_{i,j} = s_j * g_{i,j}$, the probability that an individual in size class $j$ at the current census survives to the next census and the probability that they transition. 

**Reproduction**
Reproduction combines vital rates - fertility plus the survival rate of adults and/or offspring.
There are four possible scenarios to consider:

1. **Birth-pulse populations with a pre-breeding census**: youngest class (1) will be those that were produced in the previous pulse; to contribute to the next census adults must produce newborns immediately after the census ($a_{1,j} = F_j = f_j s_0$ where $s_0$ is survival in the first year) - *a disadvantage of this method is thaht it does not allow us to investigate whether changing offspring production or newborn survival would have a greater effect on population growth*.
2. **Birth-pulse populations with a post-breeding census**: the reproductive terms are now the number of newborns that each adult in the current census will contribute to the next census - the adult must survive for a full year and then reproduce ($a_{1,j} = F_j = s_jf_j$)
3. **Birth-pulse populations with an intermediate census**: offspring are first observed at the next census - the reproduction element in the matrix is the average of the number of offspring at the next census attributable to each individual in class $j$ at the previous census (would be zero if the individual dies, their offspring dies, or they do not produce any offspring). One could parameterize a model with an intermediate pulse if they have data for probability of survival between the pulse and the census for both adults and offspring, but this needs a census of the population near the birth pulse. 
It may be reasonable to pretend that fecundity happens after it actually does - e.g. at fledging of new birds - reproduction is the survival rate of an individual at the current census times the number of *surviving* fledglings.
4. **Birth flow populations**: the simplest approach is to pretend that all offspring are born at the mid-point of the interval. 
Reproduction is then the product of
   - Probability that class $j$ survives from one census to the midpoint of the next inter-census interval (if survival is more or less constant over the year, can approximate as the square root of annual survival $\sqrt{s_j}$)
   - Average number of offspring to which each surviving $j$ individual gives birth over an inter-census interval (summed over repeated checks performed through the interval), $f_j$
   - Probability that an offspring produced at the midpoint of the inter-census period survives to the next census, approximately $\sqrt{s_0}$
   
There are more complex ways to do this.